### ISSUE TITLE
AMD E9171 GPU OPENVX USAGE

### ISSUE THREAD

**Issue by drvshavva** [KhronosGroup/openvx-samples#10]
Hi, is ti possible to use openvx with amd e9171 gpu ? If can not, do you know, how can use nnef or onnx file with this gpu ?

**Comment by kiritigowda** [comment]
@drvshavva the OpenVX sample implementation should build and run on the AMD64 system. Note that the sample only has the CPU backend for OpenVX 1.3, if you want to use the GPU use MIVisionX.
```
git clone --recursive https://github.com/KhronosGroup/OpenVX-sample-impl.git
cd OpenVX-sample-impl/
python Build.py --os=Linux --arch=64 --conf=Debug --conf_vision --enh_vision --conf_nn
```
If you want to use NNEF Import follow this sample - https://github.com/kiritigowda/OpenVX/tree/master/digitClassification#digit-classification

**Comment by drvshavva** [comment]
thanks for your answer
