### ISSUE TITLE
Unable to run application

### ISSUE THREAD

**Issue by arjunskumar** [KhronosGroup/openvx-samples#3]
While running the canny edge application in live mode, i'm getting this error

Failed to remove kernel[0]=org.khronos.extra.edge_trace
Failed to remove kernel[1]=org.khronos.extra.euclidean_nonmaxsuppression_harris
Failed to remove kernel[2]=org.khronos.extras.harris_score
Failed to remove kernel[3]=org.khronos.extras.laplacian3x3
Failed to remove kernel[4]=org.khronos.extras.image_to_list
Failed to remove kernel[5]=org.khronos.extra.nonmaximasuppression
Failed to remove kernel[6]=org.khronos.extra.elementwise_norm
Failed to remove kernel[7]=org.khronos.extras.scharr3x3
Failed to remove kernel[8]=org.khronos.extras.sobelMxN

**Comment by arjunskumar** [comment]
Working with Opencv 3.3.1 earlier I was having Opencv 3.2.0

**Comment by thrylos2307** [comment]
i am facing this error on rpi , i am having opencv 3.4.1. How did u resolve this ?

**Comment by arjunskumar** [comment]
@thrylos2307 Please refer this [steps](https://github.com/arjunskumar/openvx_ws#install-openvx-13-on-ubuntu-1804)

**Comment by kaki-epithesi** [comment]
I am facing the same error in R-pi + there is another error 
![image](https://user-images.githubusercontent.com/56767725/125441964-02797a16-a975-47c2-a974-f71c28fb3952.png)
It is working fine with local images , but accessing live camera is becoming the problem .

**Comment by arjunskumar** [comment]
@kaki-epithesi

 1) Is the live camera working? 
 2) Check your Opencv Version?

**Comment by kaki-epithesi** [comment]
> @kaki-epithesi
> 
> 1. Is the live camera working?
> 2. Check your Opencv Version?

1> live camera is working 
2> opencv version 3.4.1.

**Comment by arjunskumar** [comment]
@kaki-epithesi Can you try with opencv 3.3.1?

**Comment by kaki-epithesi** [comment]
> @kaki-epithesi Can you try with opencv 3.3.1?

i will get to that .
